# Generated by Django 4.2.1 on 2023-06-15 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('login', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('boardId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanban_api.board')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('color', models.CharField(max_length=50)),
                ('priority', models.IntegerField()),
                ('dueDates', models.DateField()),
                ('statusListId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanban_api.statuslist')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanban_api.user')),
            ],
        ),
    ]
